# Postgres and pgAdmin4 stack for development

version: '3.1'

services:

  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: apivendas-app
    ports:
      - '3333:3333'
    volumes:
      - .:/home/node/app
    depends_on:
      - db
      - redis

  redis:
    image: 'bitnami/redis:latest'
    container_name: apivendas-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "docker"
      POSTGRES_DB: "apivendas"
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@email.com"
      PGADMIN_DEFAULT_PASSWORD: "docker"
    depends_on:
      - db
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
